namespace NeuroSphere;

public enum HumanPart
{
    None,
    LeftEye,
    RightEye,
    LeftEar,
    RightEar,
    LeftArmTop,
    RightArmTop,
    LeftArmBottom,
    RightArmBottom,
    LeftHand,
    RightHand,
    LeftFootTop,
    RightFootTop,
    LeftFoot,
    RightFoot,
    LeftLegTop,
    RightLegTop,
    LeftLegBottom,
    RightLegBottom,
    // fingers
    LeftFinger1,
    LeftFinger2,
    LeftFinger3,
    LeftFinger4,
    LeftFinger5,
    RightFinger1,
    RightFinger2,
    RightFinger3,
    RightFinger4,
    RightFinger5,
    LeftShoulder,
    RightShoulder,
    Back,
    Chest,
    Head,
}